name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker
      run: docker login  -u koijas -p dckr_pat_JPp8HOBFBW_Aq6bP-MiDgSGRQBw
    - name: Build
      run: docker build . --file Dockerfile --tag v1.0:$(date +%s)
    - name: Deploy to docker
      run: docker push koijas/sua:v1.0
